name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          
      - name: Check out code
        uses: actions/checkout@v3

      - name: Test code with code coverage
        run: go test ./... -cover

  style:
    name: Style
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          
      - name: Check out code
        uses: actions/checkout@v3

      - name: Format the code
        run: go fmt ./...
      
      - name: Test the format
        run: test -z $(go fmt ./...)